CREATE SCHEMA SENSOR_MANAGER
    AUTHORIZATION POSTGRES;

CREATE TABLE SENSOR_MANAGER.SENSOR_SETUP_BASE
(
    SENSOR_ID		VARCHAR(1024),
    SENSOR_TYPE            VARCHAR(64) NOT NULL,
    SENSOR_NAME	    VARCHAR(100),
    DESCRIPTION     VARCHAR(500),
    CREATE_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATOR_ID      VARCHAR(64),
    MODIFY_DATETIME TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    MODIFIER_ID     VARCHAR(64)
    SENSOR_PARAMETER VARCHAR(1024) NOT NULL,
    NON_VALUE_SENSOR_PARAMETER VARCHAR(1024)
    VALUE_SENSOR_PARAMETER VARCHAR(1024)
    CONSTRAINT SENSOR_SETUP_BASE_PK PRIMARY KEY (ID),
    CONSTRAINT SENSOR_SETUP_BASE_UK01 UNIQUE (TYPE_URI)
)